import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Operators from "../components/Operators";
import Modal from "../components/Modal";
import { operatorType } from "../types";
import styled from "styled-components";

const operators = [
  {
    id: 1,
    name: "МТС",
    logo: "mts.png",
    payServiceURL: "https://jsonplaceholder.typicode.com/posts"
  },
  {
    id: 2,
    name: "Билаин",
    logo: "beeline.png",
    payServiceURL: "https://jsonplaceholder.typicode.com/posts"
  },
  {
    id: 3,
    name: "Мегафон",
    logo: "megafon.png",
    payServiceURL: "https://jsonplaceholder.typicode.com/posts"
  }
];

const prefix = process.env.NEXT_PUBLIC_BASE_PATH || ''

const Home: NextPage = () => {

  const [modal, setModal] = useState(false);
  const [curOperator, setCurOperator] = useState({} as operatorType);

  return (
    <div>
      <Head>
        <link rel="shortcut icon" href={prefix + '/favicon.ico'} />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <Title>Главная</Title>
        <Operators
          operators={operators}
          setModal={setModal}
          setCurOperator={setCurOperator}
        />
        {modal && <Modal curOperator={curOperator} setModal={setModal} />}
      </Wrapper>
    </div>
  );
};

export default Home;

const Wrapper = styled.div`
  padding: 20px;
  margin: 0;
  width: 100%;
  min-height: 100vh;
  background-color: #191a19;
`;

const Title = styled.h1`
  margin-top: 0;
  font-family: serif;
  font-size: 3rem;
  letter-spacing: 0.4rem;
  text-align: center;
  color: #fefefe;
`;
